on:
  push:

env:
  IMAGE: docker.pkg.github.com/${{ github.repository }}/image:latest

jobs:
  publish:
    runs-on: ubuntu-latest

    env:
      USERNAME: ${{ secrets.USERNAME }}
      PASSWORD: ${{ secrets.PASSWORD }}
      TOKEN: ${{ secrets.GITHUB_TOKEN }}

    strategy:
      matrix:
        password: [wrong-username, "${USERNAME}"]
        username: [wrong-password, "${PASSWORD}", "${TOKEN}"]

    steps:
      - name: Create a Dockerfile
        run: |
          echo 'FROM alpine' > Dockerfile
          echo 'ENTRYPOINT ["echo", "Hello from ${{ github.repository }}!"]' >> Dockerfile

      - name: Build image
        run: docker build . -t ${{ env.IMAGE }}

      - name: Login to ghcr.io
        run: docker login https://docker.pkg.github.com -u ${{ matrix.username }} --password-stdin <<< ${{ matrix.password }}

      - name: Publish image
        run: docker push ${{ env.IMAGE }}
