on:
  push:

env:
  IMAGE: docker.pkg.github.com/${{ github.repository }}/image:latest

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Create a Dockerfile
        run: |
          echo 'FROM alpine' > Dockerfile
          echo 'ENTRYPOINT ["echo", "Hello from ${{ github.repository }}!"]' >> Dockerfile

      - name: Build image
        run: docker build . -t ${{ env.IMAGE }}

      - name: Login to ghcr.io
        run: docker login https://docker.pkg.github.com -u ${{ secrets.USERNAME }} --password-stdin <<< xxx

      - name: Publish image
        run: docker push ${{ env.IMAGE }}
