on:
  push:

env:
  IMAGE: docker.pkg.github.com/${{ github.repository }}/docker-password-login:latest

jobs:
  publish:
    runs-on: ubuntu-latest


    strategy:
      fail-fast: false
      matrix:
        username: [wrong-username, "$USERNAME"]
        password: [wrong-password, "$PASSWORD", "$TOKEN"]

    steps:
      - name: Create a Dockerfile
        run: |
          echo 'FROM alpine' > Dockerfile
          echo 'ENTRYPOINT ["echo", "Hello from ${{ github.repository }}!"]' >> Dockerfile

      - name: Build image
        run: docker build . -t ${{ env.IMAGE }}

      - name: Login to ghcr.io
        run: echo ${{ matrix.password }} | docker login https://docker.pkg.github.com -u ${{ matrix.username }} --password-stdin
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish image
        run: docker push ${{ env.IMAGE }}
